Repository dwyl/auth_plug, pull requests merged in 2022-11, with the labels that each got.

#77 PR: Downgrade plug version for phoenix compatibility issue #76
  README.md
  lib/auth_plug.ex
  mix.exs
Labels: awaiting-review, chore, T5m

#84 PR: `:loggedin false` issue #83
  .env_sample
  .github/workflows/ci.yml
  CONTRIBUTING.md
  README.md
  lib/auth_plug.ex
  lib/auth_plug_optional.ex
  lib/token.ex
  mix.exs
  test/auth_plug_optional_test.exs
  test/auth_plug_test.exs
Labels: enhancement, awaiting-review, chore, priority-2, technical, T5m

#88 [PR] Assigns helper
  README.md
  lib/auth_plug.ex
  mix.exs
  mix.lock
  test/auth_plug_test.exs
Labels: enhancement, awaiting-review, chore

#89 Socket assigns helper issue #86
  .env_sample
  README.md
  config/test.exs
  lib/auth_plug.ex
  lib/auth_plug_helpers.ex
  lib/token.ex
  mix.exs
  test/auth_plug_helpers_test.exs
  test/auth_plug_test.exs
  test/test_helper.exs
Labels: awaiting-review
