Repository dwyl/auth_plug, pull requests merged in 2023-01, with the labels that each got.

#102 [PR] Adding section to explain how to work with an API.
  README.md
Labels: enhancement

#104 Instructions for how to make `AUTH_API_KEY` available to @dependabot
  README.md
Labels: enhancement, awaiting-review, chore, T5m

#107 Manage post request error
  lib/auth_plug.ex
  lib/auth_plug_helpers.ex
  lib/auth_plug_optional.ex
  lib/httpoison_mock.ex
  mix.exs
  test/auth_plug_helpers_test.exs
  test/auth_plug_test.exs
Labels: awaiting-review
